apiVersion: batch/v1
kind: Job
metadata:
  name: data-prep-cpu
  namespace: fraud-det-v31
  labels:
    component: pipeline
    stage: prep-cpu
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: data-prep-cpu
        component: pipeline
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: slc6-lg-n3-b30-29
      containers:
        - name: data-prep-cpu
          image: 10.23.181.247:5000/fraud-det-v31/data-prep-cpu:latest
          imagePullPolicy: Always
          env:
            - name: INPUT_PATH
              value: /data/raw
            - name: OUTPUT_PATH
              value: /data/features-cpu
          volumeMounts:
            - name: raw-data
              mountPath: /data/raw
              readOnly: true
            - name: features-cpu-data
              mountPath: /data/features-cpu
      volumes:
        - name: raw-data
          persistentVolumeClaim:
            claimName: raw-data-pvc
        - name: features-cpu-data
          persistentVolumeClaim:
            claimName: features-cpu-data-pvc
