apiVersion: batch/v1
kind: Job
metadata:
  name: data-gather
  namespace: fraud-det-v31
  labels:
    component: pipeline
    stage: gather
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: data-gather
        component: pipeline
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: slc6-lg-n3-b30-29
      containers:
        - name: data-gather
          image: 10.23.181.247:5000/fraud-det-v31/data-gather:latest
          imagePullPolicy: Always
          env:
            - name: OUTPUT_PATH
              value: /data/raw
            - name: RUN_MODE
              value: once
            - name: NUM_WORKERS
              value: "2"
            - name: CHUNK_SIZE
              value: "10000"
            - name: TARGET_ROWS
              value: "1000000"
            - name: TARGET_ROWS_PER_SEC
              value: "10000"
            - name: KAGGLE_SEED_PATH
              value: /app/seed-data/credit_card_transactions.csv.zip
          volumeMounts:
            - name: raw-data
              mountPath: /data/raw
      volumes:
        - name: raw-data
          persistentVolumeClaim:
            claimName: raw-data-pvc
